### ISSUE TITLE
Duplicate SID - 'MALWARE [PTsecurity] Backdoor.Java.Adwind.cu Certificate flowbit set 1'

### ISSUE THREAD

**Issue by novaksam** [ptresearch/AttackDetection#12]
Ran into an issue when using these in conjunction with EmergingThreats and Scirius.

pt-rules.rules
>./git-sources/3/rules/pt-rules.rules:alert  tls $EXTERNAL_NET any -> $HOME_NET any ( msg: "MALWARE [PTsecurity] Backdoor.Java.Adwind.cu Certificate flowbit set 1"; flow: established, to_client;content: "|3082|";depth:300; content: "|3082|";distance:2;within:2; content: "|a00302010202|";distance:2;within:6; flowbits: set, FB332502_; flowbits: noalert; threshold: type limit, track by_src, count 1, seconds 30;  metadata: former_category TROJAN; reference:md5,56e42156a1676b34f5350c01e34875d1; classtype:trojan-activity; reference: url, github.com/ptresearch/AttackDetection; metadata: Open Ptsecurity.com ruleset; sid: 2024751; rev:3; metadata:affected_product Windows_XP_Vista_7_8_10_Server_32_64_Bit, attack_target Client_Endpoint, deployment Perimeter, signature_severity Major, created_at 2017_09_21, malware_family Adwind, performance_impact Moderate, updated_at 2018_01_30;)

trojan.rules:
>./git-sources/31/rules/trojan.rules:#alert tcp $EXTERNAL_NET [:32768] -> $HOME_NET any (msg:"ET TROJAN [PTsecurity] Backdoor.Java.Adwind.cu Certificate flowbit set 1"; flow:established, to_client; content:"|308204|"; depth:300; content:"|308203|"; distance:1; within:3; content:"|a0030201020204|"; distance:1; within:7; content:"|300d06092a864886f70d01010b05003081|"; distance:4; within:17; flowbits:set,FB332502_; flowbits:noalert; threshold:type limit, track by_src, count 1, seconds 30; metadata: former_category TROJAN; reference:md5,d93dd17a9adf84ca2839708d603d3bd6; classtype:trojan-activity; sid:2024751; rev:1; metadata:affected_product Windows_XP_Vista_7_8_10_Server_32_64_Bit, attack_target Client_Endpoint, deployment Perimeter, signature_severity Major, created_at 2017_09_21, malware_family Adwind, performance_impact Moderate, updated_at 2017_09_21;)

The conflict is preventing the rules from compiling correctly for Scirius.

**Comment by ptresearch** [comment]
Thank's that you noticed. Now fixed!
