### ISSUE TITLE
rules metadata format

### ISSUE THREAD

**Issue by kulikov-a** [ptresearch/AttackDetection#22]
Hi.
some rules have strange metadata
eg
"metadata: id_140409,created_at 2017_6_2, url, https://blog.fortinet.com/2016/07/27/bayrob-an-ancient-evil-awakens-ii"
(metadata "url" comma separated from value ("..blog.frtinet.."); metadata (id_140409) without value)
is it error in metadata format?
I guess the metadata should look like
"metadata: param value, param2 value2 "

**Comment by ptresearch** [comment]
Hi @kulikov-a. No error, suricata says "While the format is free-form, it is recommended to stick to key, value pairs as Suricata can include these in eve alerts.". So we did when we started putting metadata in our rules in free format. Now we moved to key-value metadata format.

https://github.com/ptresearch/AttackDetection/commit/9245ba7574e5dd783be2585bb9667dbe7b12c337

**Comment by kulikov-a** [comment]
thanks!
