### ISSUE TITLE
SID range in Readme doesn't correspond to repository's

### ISSUE THREAD

**Issue by cccs-julie** [ptresearch/AttackDetection#24]
I noticed the [SID range mentioned in your README.md file](https://github.com/ptresearch/AttackDetection#sid-range) doesn't match with the rules in the repository.
```  
SID range
We use SID 10000000-10999999 for our rules.
```  
There are some rules in the repository going beyond that range. Would it be possible to put your true SID range in the README.md file, or to fix the rules having an SID in the 11 millions, 20 millions and 21 millions range?  
Thank you!

**Comment by ptresearch** [comment]
Hi @cccs-julie , we moved our 2xxxxxxx rules into 111xxxxx range and expanded sid range to 10000000-11999999. Thanks for contributing!
