### ISSUE TITLE
how to setting DC_SERVERS?

### ISSUE THREAD

**Issue by vncloudsco** [ptresearch/AttackDetection#25]
``` # Note1: Please, set $DC_SERVERS address group in suricata.yaml config, so Active Directory rules could work properly. ```

How can I install this on suricata 6.0.3? I don't know how to configure?

**Comment by malinkinsa** [comment]
Hello,
In your suricata.yaml  (/etc/suricata/suricata.yaml) in block (address-groups:) where _HOME_NET, EXTERNAL_NET_ you must create a simmilar line with name _DC_SERVERS_ and IP addresses of your DC. For example something like this:
```
HOME_NET: "[$some_ips$]"
EXTERNAL_NET: "!$HOME_NET"
DC_SERVERS: "[IP address of your DC servers]"
```

**Comment by vncloudsco** [comment]
thank you i made it,
