### ISSUE TITLE
Вопрос по правилам

### ISSUE THREAD

**Issue by GrinblatAP** [ptresearch/AttackDetection#26]
Добрый день. Как и куда вставлять эти правила: apt31.rules?

**Comment by ptresearch** [comment]
Добрый вечер. Эти правила были разработаны во время изучения инструментов группировки APT31. Из-за различий в IDS системах мы были вынуждены написать две версии для Suricata и для Snort, поэтому используйте одну из версий, а другие правила выключите.
Об этом исследовании вышла статья в нашем блоге: https://www.ptsecurity.com/ww-en/analytics/pt-esc-threat-intelligence/apt31-new-attacks/
