### ISSUE TITLE
SID used are for local use

### ISSUE THREAD

**Issue by regit** [ptresearch/AttackDetection#3]
From http://doc.emergingthreats.net/bin/view/Main/SidAllocation, it seems the range of SID used is reserved for local use. So it may be better to use another one. I don't know how allocation is working for this but it would be nice if you had your own range.

**Comment by ptresearch** [comment]
Hello Eric,
The range of SID used is reserved for local use starts from 1 million, that's why we start our range from 10 millions.

Thanks for the issue. Looks like we need to add an entry to http://doc.emergingthreats.net/bin/view/Main/SidAllocation

**Comment by regit** [comment]
Outh sorry, looks like I forgot one zero. It will be good indeed if you could updated SidAllocation page.

**Comment by ptresearch** [comment]
We added info about SID range into the Readme https://github.com/ptresearch/AttackDetection/commit/4900f61ac65d5b2465617afd3c47cc36337328c9
