### ISSUE TITLE
Fasle positive for ET TROJAN [PTsecurity] Malicious SSL connection (Upatre Downloader CnC) cert

### ISSUE THREAD

**Issue by L1ghtn1ng** [ptresearch/AttackDetection#7]
If you go to the following site phoronix.com and browse the site your get this in my suricata logs 
ET TROJAN [PTsecurity] Malicious SSL connection (Upatre Downloader CnC) cert

The only thing I can tell is its due to the cloudflare SSL cert with loads of domains in the alt san field of the cert

**Comment by ostjn** [comment]
This signature set no alert flowbits, how can it generate an alert?
ET TROJAN [PTsecurity] Malicious SSL connection (Upatre Downloader CnC) **cert** sid 2024772 
This signature serves as the first link in the chain of signatures. which end either with an alert 2024777, 2024778 or 2024776. What is the sid of a foul signature?

**Comment by kirillwow** [comment]
@L1ghtn1ng Any additional info regarding foul signature ?

**Comment by ostjn** [comment]
Ok. 
    Signature with "cert" does not generate an alert. It is part of a set of several signatures interconnected by flowbits. The entire chain of these signatures checks the distribution of fragment lengths in the encrypted connection. And if it satisfies what is described in the rules, then the last in chain signature generates an alert.
       While the concept of the last signature is rather arbitrary. Since all signatures check the packet. We in our signatures use positioning in the stream stream_size, shifting the flow_bits settings to the positions where the required packets are located. Thank you for your interest. I hope you do not modify our signatures? Otherwise they can work unpredictably.

**Comment by L1ghtn1ng** [comment]
No I do not modify your rules and I did look for the Sid's you gave me and they do not show up in my logs. So I am not sure what else to do. I did disable that rule as I was not getting any alerts regarding this till your rules got added to the main ET ruleset.

Any suggestions you have I am more than happy to help find the issue with the rule??
________________________________

**Comment by ostjn** [comment]
I'm trying to reproduce alert. If you have a dump of traffic, give the link.

**Comment by L1ghtn1ng** [comment]
I do not have a dump of traffic but you should be able to generate the alert via this link <https://www.google.com/url?q=http://www.pets4homes.co.uk&sa=D&source=hangouts&ust=1525172558966000&usg=AFQjCNFh-yRNkOBSU5U6NN5PL8rZZjr5Fw> www.pets4homes.co.uk<http://www.pets4homes.co.uk>
________________________________

**Comment by ostjn** [comment]
There are no alert. Specify the exact number of the **sid** from the alert. 
I see only the platform cPanel, which once matches the first rule with "... Downloader CnC) **cert**" 
PCAP link: https://www.dropbox.com/s/5mhqso9avo3cxna/02853518-22d9-4951-8fc8-0fc592368626_1.pcap?dl=0

**Comment by NomadSecurity** [comment]
I am seeing this same alert in my Suricata logs if I try to browse to the following website. https://www.sorensonmedia.com/login
Alert Sid 2024772
Not sure where to proceed from here. I am not keen on disabling the rule.

**Comment by ostjn** [comment]
**Hello. Explain please how do you get so this rule generates an alert at all? 
He has a flag not to cause an alert !!!**
alert tcp $EXTERNAL_NET 443 -> $HOME_NET any (msg:"ET TROJAN [PTsecurity] Malicious SSL connection (Upatre Downloader CnC) cert"; flow:established,to_client; content:"|30 82|"; depth:300; content:"|a0 03 02 01 02 02|"; distance:6; within:6; content:"|63 50 61 6e 65 6c 2c 20 49 6e 63|"; distance:60; within:120; fast_pattern;  flowbits:set,FB346039_0; **flowbits:noalert;** metadata: former_category TROJAN; classtype:trojan-activity; **sid:2024772**; rev:2; metadata:affected_product Windows_XP_Vista_7_8_10_Server_32_64_Bit, attack_target Client_Endpoint, deployment Perimeter, signature_severity Major, created_at 2017_09_27, malware_family Upatre, performance_impact Moderate, updated_at 2017_09_27;)

**Comment by kirillwow** [comment]
@NomadSecurity which log did you look?

**Comment by NomadSecurity** [comment]
I am running an OPNsense Firewall with Suricata IDS enabled. These alerts were visible on the IDS Alerts screen. Interestingly, I have checked to see if the alerts are still occurring, when I browse to the offending Sorenson web site, but now there are no alerts and Traffic is not blocked. I also tested this with two other websites known to trigger the problem, but now there is no problem. I cannot explain this behaviour except to say there have been a number of firmware updates to the firewall and possibly IDS rule updates as well.

**Comment by kirillwow** [comment]
@NomadSecurity didnt you just disabled that signature ?) Could you please check if signature sid 2024772 is still active and contains flowbits:noalert keyword inside? That's would be much helpful!

**Comment by NomadSecurity** [comment]
It is possible that the rule was not active. I have retested with rule active and yes the alert is back and traffic is blocked. Two more sites that trigger the alerts https://superpro.com.au  and  https://www.pradopoint.com.au
Copy of the rules is listed below, copied directly from the emerging-trojan.rules file on Firewall.
 
drop  tcp $EXTERNAL_NET 443 -> $HOME_NET any (msg:"ET TROJAN [PTsecurity] Malicious SSL connection (Upatre Downloader CnC) cert"; flow:established,to_client; content:"|30 82|"; depth:300; content:"|a0 03 02 01 02 02|"; distance:6; within:6; content:"|63 50 61 6e 65 6c 2c 20 49 6e 63|"; distance:60; within:120; fast_pattern;  flowbits:set,FB346039_0; flowbits:noalert; metadata: former_category TROJAN; classtype:trojan-activity; sid:2024772; rev:2; metadata:affected_product Windows_XP_Vista_7_8_10_Server_32_64_Bit, attack_target Client_Endpoint, deployment Perimeter, signature_severity Major, created_at 2017_09_27, malware_family Upatre, performance_impact Moderate, updated_at 2017_09_27;)

**Comment by ostjn** [comment]
The first thing that comes to mind is the action "drop". Drop the packet should the last rule in the chain.  Because this is an obvious malfunction, possible we have to start a bug.  I dare to assume that if you set this rule to "alert" action, then it will start processing the "flowbits:noalert". Please tell me the version of the suricata so what i can reproduse this bug .

**Comment by NomadSecurity** [comment]
I think this issue is of my own making. I think I have incorrectly configured rule actions without fully understanding how each rule should be used. In answer to your question I am using Suricata Ver 4.0.4 running on OPNSense Ver 18.1.9.
Your assumption was correct. Changing the action to "alert" stopped the log entries and allowed the traffic to pass.
Is it fair to say that a rule that has "flowbits:noalert" set, should under normal conditions, not have the action set to "drop", as the result of this rule is used to in conjunction with one or more following rules, to find a match. Hence as you say the last rule in the sequence has the drop action. If this is indeed the case, then the implementation of Suricata in OPNSense is a trap for young players, as it is all too easy to set a bulk "drop" action on all rules within a Rules Collections/Groups.

**Comment by L1ghtn1ng** [comment]
I would not say that it is an OPNsense bug more of suricata one as even if a rule is set to drop that should be ignored when the flowbits noalert is set
________________________________

**Comment by NomadSecurity** [comment]
You may well be right. Determining who is best placed to add extra intelligence to rule configuration or interpretation is way above my pay scale. Maybe the clever people at both OPNsense and Suricata will get together to work on an improved implementation.
Thank you for helping me understand.
