### ISSUE TITLE
when i run suricata-update to update ptresearch/attackdetection rules,Suricata test failed.

### ISSUE THREAD

**Issue by Raul1718** [ptresearch/AttackDetection#8]
look the picture:
[![QQ_20180428185149.png](https://s9.postimg.cc/4mrw7mju7/QQ_20180428185149.png)](https://postimg.cc/image/86dtxfmjv/)

**Comment by jmtaylor90** [comment]
From your screenshot it looks like you may just need to define the DC_SERVERS variable in your suricata yaml file to fix your issue.

**Comment by Raul1718** [comment]
@jmtaylor90 yes.But i don't know what DC_SERVERS means.And how to set in my suricata yaml

**Comment by jmtaylor90** [comment]
Ah okay. DC_SERVERS is a variable that denotes the Domain Controller servers in your environment.

The format would be the same as HOME_NET, so for example (under the "address-groups" heading) you would want to add:

DC_SERVERS: "[10.0.0.2/32,192.168.0.1/32]"

Of course you will want to change 10.0.0.2/32 and 192.168.0.1/32 to whatever the IP addresses are of your Domain Controllers are and just separate the values by a comma.

Also for reference:
https://raw.githubusercontent.com/OISF/suricata/master/suricata.yaml.in

**Comment by kirillwow** [comment]
@Raul1718 This issues was fixed in suricata-update (see https://github.com/OISF/suricata-update/pull/31). They disable signatures with unknown variables and print a note about that since that pull. So update.
